<?php

/**
 * Name: WOPI
 * Description: Basic implementation of a WOPI host. Tested with collabora, other clients might or might not work at the moment.
 * Version: 0.1-beta
 * Author: Mario Vavti
 * Maintainer: Mario Vavti
 */


use Zotlabs\Extend\Hook;
use Zotlabs\Extend\Route;
use Zotlabs\Lib\Config;
use Zotlabs\Lib\Cache;

function wopi_install() {
	Route::register('addon/wopi/Mod_Wopi.php', 'wopi');
	Hook::register('content_security_policy','addon/wopi/wopi.php','wopi_content_security_policy');
	Hook::register('construct_page', 'addon/wopi/wopi.php', 'wopi_construct_page');
}


function wopi_uninstall() {
	Route::unregister('addon/wopi/Mod_Wopi.php', 'wopi');
	Hook::unregister('content_security_policy','addon/wopi/wopi.php','wopi_content_security_policy');
	Hook::unregister('wopi_construct_page', 'addon/wopi/wopi.php', 'wopi_construct_page');
}

function wopi_plugin_admin(&$o) {
	$t = get_markup_template('admin.tpl', 'addon/wopi/');

	$wopi_client_url = Config::Get('system', 'wopi_client_url', '');

	$o = replace_macros($t, [
		'$submit' => t('Submit'),
		'$wopi_client_url' => ['wopi_client_url', t('URL of the WOPI client'), $wopi_client_url, t('E.g. https://collabora.example.com (this hub must be whitelisted at the WOPI client)')]
	]);
}

function wopi_plugin_admin_post() {
	$wopi_client_url = isset($_POST['wopi_client_url']) ? notags(trim($_POST['wopi_client_url'])) : '';
	Config::Set('system', 'wopi_client_url', $wopi_client_url);
}

function wopi_content_security_policy(&$arr) {
	$wopi_client_url = Config::Get('system', 'wopi_client_url', '');

	if (!$wopi_client_url) {
		return;
	}

	$arr['frame-src'][] = parse_url($wopi_client_url , PHP_URL_HOST);
}

function wopi_construct_page(&$arr) {
	$wopi_client_url = Config::Get('system', 'wopi_client_url', '');

	if (!$wopi_client_url) {
		return;
	}

	$wopi_supported_types = Cache::get('wopi_supported_mime_types', '1 Day');

	if (!$wopi_supported_types) {
		// Fallback generated by Mod_wopi::cache_supported_types() from collabora version: 25.04.8.1
		$wopi_supported_types = '["image\/svg+xml","application\/vnd.ms-powerpoint","application\/vnd.ms-excel","application\/vnd.sun.xml.writer","application\/vnd.oasis.opendocument.text","application\/vnd.oasis.opendocument.text-flat-xml","application\/vnd.sun.xml.calc","application\/vnd.oasis.opendocument.spreadsheet","application\/vnd.oasis.opendocument.spreadsheet-flat-xml","application\/vnd.sun.xml.impress","application\/vnd.oasis.opendocument.presentation","application\/vnd.oasis.opendocument.presentation-flat-xml","application\/vnd.sun.xml.draw","application\/vnd.oasis.opendocument.graphics","application\/vnd.oasis.opendocument.graphics-flat-xml","application\/vnd.oasis.opendocument.chart","application\/vnd.sun.xml.writer.global","application\/vnd.oasis.opendocument.text-master","application\/vnd.sun.xml.writer.template","application\/vnd.oasis.opendocument.text-template","application\/vnd.oasis.opendocument.text-master-template","application\/vnd.sun.xml.calc.template","application\/vnd.oasis.opendocument.spreadsheet-template","application\/vnd.sun.xml.impress.template","application\/vnd.oasis.opendocument.presentation-template","application\/vnd.sun.xml.draw.template","application\/vnd.oasis.opendocument.graphics-template","application\/msword","application\/msword","application\/vnd.ms-excel","application\/vnd.ms-powerpoint","application\/vnd.openxmlformats-officedocument.wordprocessingml.document","application\/vnd.ms-word.document.macroEnabled.12","application\/vnd.openxmlformats-officedocument.wordprocessingml.template","application\/vnd.ms-word.template.macroEnabled.12","application\/vnd.openxmlformats-officedocument.spreadsheetml.template","application\/vnd.ms-excel.template.macroEnabled.12","application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application\/vnd.ms-excel.sheet.binary.macroEnabled.12","application\/vnd.ms-excel.sheet.macroEnabled.12","application\/vnd.openxmlformats-officedocument.presentationml.presentation","application\/vnd.ms-powerpoint.presentation.macroEnabled.12","application\/vnd.openxmlformats-officedocument.presentationml.template","application\/vnd.ms-powerpoint.template.macroEnabled.12","application\/vnd.wordperfect","application\/x-aportisdoc","application\/x-hwp","application\/vnd.ms-works","application\/vnd.ms-office","application\/x-mswrite","application\/x-dif-document","text\/spreadsheet","text\/csv","application\/x-dbase","application\/vnd.lotus-1-2-3","image\/cgm","image\/vnd.dxf","image\/x-emf","image\/x-wmf","application\/coreldraw","application\/vnd.visio2013","application\/vnd.visio","application\/vnd.ms-visio.drawing","application\/x-mspublisher","application\/x-sony-bbeb","application\/x-gnumeric","application\/macwriteii","application\/x-iwork-numbers-sffnumbers","application\/vnd.oasis.opendocument.text-web","application\/x-pagemaker","text\/rtf","text\/plain","application\/x-fictionbook+xml","application\/clarisworks","image\/x-wpg","application\/x-iwork-pages-sffpages","application\/vnd.openxmlformats-officedocument.presentationml.slideshow","application\/x-iwork-keynote-sffkey","application\/x-abiword","image\/x-freehand","application\/vnd.sun.xml.chart","application\/x-t602","image\/bmp","image\/png","image\/gif","image\/tiff","image\/jpg","image\/jpeg","application\/pdf"]';
	}

	if ($arr['module'] === 'cloud') {
		App::$page['htmlhead'] .= "<script>var wopiBaseURL = '$wopi_client_url'; var wopiSupportedTypes = $wopi_supported_types;</script>";
		App::$page['htmlhead'] .= "<script src='/addon/wopi/view/js/wopi.js'></script>";
	}
}
